### ISSUE TITLE
Ansible-core version bump in upstream kolla-ansible causes version error

### ISSUE THREAD

**Issue by OgarOgarovic** [SovereignCloudStack/kolla-builder#5]
Upstream kolla-ansible [bumped](https://opendev.org/openstack/kolla-ansible/commit/1d3b4f7b2de7836d41700de272dad3e385a6ac80) ansible-core version to 2.16 - 2.17, which now causes version error when deploying using latest commits from master and branches.

I updated ansible-core package in used virtual environment to 2.17.3 and also edited the min, max variables in the kolla-ansible script in the same environment in the kolla-builder image. I tested and uploaded the image to pluscloud into a neighboring [container](https://api.gx-scs.sovereignit.cloud:8080/swift/v1/AUTH_0b3c75f80b6743778daccec0da423465/Kolla%20Builder%20Image%2020240819/kolla-image-2024-08-19.qcow2
) to the currently linked one so it can be linked also. 

As this newer image is incompatible with deployments from older versions of kolla-ansible, maybe both images could be linked here...

**Comment by MatusJenca2** [comment]
There's another issue with the image related to [docker-python](https://github.com/docker/docker-py/issues/3256).
So we need to make sure that the version of `requests` library is  older than `2.32`
`pip install requests<2.32`

I will upload the fixed image to the container
